### ISSUE TITLE
Records are not displaying when browsing by genre

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/ceww#70]
**Describe the bug**
When I browse items by genre the first tab (Books) is not displaying results. 

**To Reproduce**
1. Go to Browse
2. Click on Genre and select Fiction
3. Note that the Books tab is empty
4. Select Collection
5. Go back to Books. Now the tab is populated

**Expected behavior**
I would expect the Book tab to be populated after I perform step 2 above. 

**Screenshots**
![image](https://user-images.githubusercontent.com/57373524/115050034-349b3c00-9e90-11eb-90ce-4bf36681f7d9.png)

**Additional context**
I'm using Firefox 87.0 on MacOS BigSur 11.2.3

**Comment by ubermichael** [comment]
That's a good bug report!

But it does work for me, although it is quite slow. I had to click on the Collection tab and then back to the Books tab. Can you try that and see if it works for you?

I think the bigger issue is in the design of the page. Right now we're showing thousands of titles in those tabs which is taxing the browser.
